name: easy_comment
description: "Provides easy to build comment functionaltiy for Flutter and Firebase."
version: 0.0.7
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  easy_helpers: ^0.0.11
  easy_locale: ^0.0.11
  easy_storage: ^0.0.19
  easyuser: ^0.0.27
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_ui_database: ^1.4.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_comment
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - firebase
  - post
  - comment
  - forum
  - blog
