name: easy_comment
description: "A comment package for Flutter and Firebase."
version: 0.0.1
homepage: https://github.com/thruthesky/easy_packages/easy_comment

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  easy_helpers: ^0.0.3
  easy_storage: ^0.0.6
  easyuser: ^0.0.10
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
