name: easy_comment
description: "Provides easy to build comment functionaltiy for Flutter and Firebase."
version: 0.0.2
homepage: https://github.com/thruthesky/easy_packages/easy_comment

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  collection: ^1.18.0
  easy_helpers: ^0.0.3
  easy_storage: ^0.0.7
  easyuser: ^0.0.10
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
