name: easychat
description: "Full featured and complete chat package for Flutter and Firebase"
version: 0.0.5
homepage: https://github.com/thruthesky/easychat

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  easy_helpers: ^0.0.3
  easy_locale: ^0.0.3
  easy_storage: ^0.0.2
  easyuser: ^0.0.7
  firebase_core: ^3.1.1
  firebase_database: ^11.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
