name: easy_forum
description: "An easy to use forum package for Flutter and Firebase."
version: 0.0.1
homepage: https://github.com/thruthesky/easy_frame/tree/main/easy_forum

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  easy_helpers: ^0.0.3
  easy_storage: ^0.0.4
  easyuser: ^0.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
