name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.2
  easy_task:
    path: ..
  easyuser: ^0.0.7
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
