name: easy_like
description: "An esay way to handle the like functionality for every use case"
version: 0.0.4
homepage: https://github.com/thruthesky/easy_frame/tree/main/easy_like

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
