name: easy_like
description: "An esay way to handle the like functionality for every use case"
version: 0.0.8
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  easy_realtime_database: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_like
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - firebase
  - like
  - dislike
  - forum
  - easy-packages
