name: easy_task
description: "A complete and easy to use task management system from the personal tasks to school and office works"
version: 0.0.4
homepage: https://github.com/thruthesky/easy_frame/tree/main/easy_task

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  easy_comment: ^0.0.5
  easy_helpers: ^0.0.9
  easy_locale: ^0.0.6
  easy_storage: ^0.0.10
  easyuser: ^0.0.17
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
