name: easy_task
description: "A TODO like task management system that allows users to create, update, delete and view tasks."
version: 0.0.1
homepage: https://github.com/thruthesky/easy_frame/tree/main/easy_task

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.0
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
