name: easy_messaging
description: "Provides an easy way of handling Firebase Cloud Messaging service"
version: 0.0.1
homepage: https://github.com/thruthesky/easy-packages/main/tree/easy_messaging

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  easy_helpers: ^0.0.10
  firebase_auth: 5.1.1
  firebase_database: 11.0.2
  firebase_messaging: 15.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
