name: easy_user_setting
description: "Easy setting management. It provides UI widgets and logics that work on Firestore"
version: 0.0.5
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_realtime_database: ^0.0.8
  firebase_database: ^11.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_user_setting
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - settings
  - configs
  - firebase
  - user-settings
  - easy-packages
