name: easy_date_picker
description: "A simple and easy to use date-picker widget"
version: 0.0.1
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_date_picker
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - firebase
  - post
  - comment
  - blog
  - easy-packages
