name: easy_setting_v2
description: "Easy setting management. It provides UI widgets and logics that work on Firestore"
version: 0.0.1
homepage: https://github.com/thruthesky/easy_frame/tree/main/easy_setting

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
