name: easy_helpers
description: "Provides helper classes, functions, and extensions for easy to build flutter apps."
version: 0.0.5
homepage: https://github.com/thruthesky/easy_frame/tree/main/easy_helpers

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  devicelocale: ^0.7.1
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
